### PR TITLE
Socket Implemented By Go

### PR DESCRIPTION
**Pull request by TokioXx**

### CODE REVIEW

**Comment by Coveno6** [comment]
Reviewed by: Kevin Deems, Jonathan Minkin, Zach Coveno

Client:
  - [ ] Follows correct protocol and works with official server
  - [ ] (Optional) Also works with XXXXX language server
  - [ ] Prints useful error if server is unavailable
  - [ ] Accepts hostname and port as command line arguments
  - [ ] Prints useful error on invalid arguments
  - [ ] Includes *useful* comments, no extraneous commented out code, etc
  - [ ] No dead code. Excess code that is never run should be removed.
  - [ ] No excess console output.
  
General:
  - [ ] Readme explains socket API *clearly*
  - [ ] Readme includes student names
  - [ ] Folder is correctly named after language
  - [ ] File names follow `HelloLanguage` spec

(Optional) Server:
  - [ ] Follows correct protocol and works with official client
  - [ ] Accepts port as command line argument
  - [ ] Prints useful error on invalid arguments
  - [ ] Includes *useful* comments, no extraneous commented out code, etc

Comments or issues to be resolved:

**Comment by Coveno6** [comment]
Reviewed by: Kevin Deems, Jonathan Minkin, Zach Coveno

Client:
  - [ ] Follows correct protocol and works with official server
  - [X] (Optional) Also works with GO language server
  - [ ] Prints useful error if server is unavailable
  - [X] Accepts hostname and port as command line arguments
  - [X] Prints useful error on invalid arguments
  - [ ] Includes *useful* comments, no extraneous commented out code, etc
  - [X] No dead code. Excess code that is never run should be removed.
  - [X] No excess console output.
  
General:
  - [X] Readme explains socket API *clearly*
  - [X] Readme includes student names
  - [X] Folder is correctly named after language
  - [ ] File names follow `HelloLanguage` spec

(Optional) Server:
  - [X] Follows correct protocol and works with official client
  - [X] Accepts port as command line argument
  - [X] Prints useful error on invalid arguments
  - [ ] Includes *useful* comments, no extraneous commented out code, etc

Comments or issues to be resolved:
How to Run has type "clinet" --> "client"
Client Sends to official server but doesn't receive goodbye message

**Comment by TokioXx** [comment]
@Coveno6 All problems have been fixed

**Comment by twood02** [comment]
@freebyron - the Readme instructions for building the code are incorrect (wrong file names).  Please fix and then I will merge.

**Comment by twood02** [comment]
also, please remove the compiled executables from the repository

**Comment by TokioXx** [comment]
@twood02  All problems have been fixed

**Pull request merged**
