### PR TITLE
helloJava Submission

### PR DESCRIPTION
**Pull request by EthanBaron14**

### CODE REVIEW

**Comment by EthanBaron14** [comment]
This was made by Ethan Baron and Catherine Meadows. Sorry, forgot to include that one.

**Comment by bdevierno1** [comment]
Ben is also in this group

**Comment by dennisafa** [comment]
Reviewed by: Dennis (@git dennisafa), Deep (@git ratnadeepb)

Client:
  - [x] Follows correct protocol and works with official server
  - [x] (Optional) Also works with XXXXX language server
  - [x] Prints useful error if server is unavailable
  - [x] Accepts hostname and port as command line arguments
  - [ ] Prints useful error on invalid arguments
  - [x] Includes *useful* comments, no extraneous commented out code, etc
  - [x] No dead code. Excess code that is never run should be removed.
  - [x] No excess console output.
  
General:
  - [x] Readme explains socket API *clearly*
  - [ ] Readme includes student names
  - [x] Folder is correctly named after language
  - [x] File names follow `HelloLanguage` spec

(Optional) Server:
  - [ ] Follows correct protocol and works with official client
  - [ ] Accepts port as command line argument
  - [ ] Prints useful error on invalid arguments
  - [ ] Includes *useful* comments, no extraneous commented out code, etc

Comments or issues to be resolved:
Error check on when no command line arguments are passed.

**Comment by twood02** [comment]
The readme says you can use 
```
To run, use command `java Client` or `./Client`
```
but `./Client` won't work - remove this.

Please also delete the .class file and just include your source file.

**Comment by bdevierno1** [comment]
> The readme says you can use
> 
> ```
> To run, use command `java Client` or `./Client`
> ```
> 
> but `./Client` won't work - remove this.
> 
> Please also delete the .class file and just include your source file.

I've amended the errors as per suggestions. @EthanBaron14 @catherinemeadows

**Pull request merged**
