### PR TITLE
Bramlett/Nalla HelloPython 1/28/20

### PR DESCRIPTION
**Pull request by katiebramlett**
Katie Bramlett & Sreya Nalla
HelloPython - CS 3907
1/28/20

### CODE REVIEW

**Comment by ldierksheide** [comment]
Reviewed by: Linnea Dierksheide (@ldierksheide), Tuhina Dasgupta (@tuhinadasgupta), Becky Shanley (@rebeccc)

Client:
  - [x] Follows correct protocol and works with official server
  - [ ] (Optional) Also works with XXXXX language server
  - [x] Prints useful error if server is unavailable
  - [x] Accepts hostname and port as command line arguments
  - [x] Prints useful error on invalid arguments
  - [x] Includes *useful* comments, no extraneous commented out code, etc
  - [x] No dead code. Excess code that is never run should be removed.
  - [x] No excess console output.
  
General:
  - [x] Readme explains socket API *clearly*
  - [x] Readme includes student names
  - [x] Folder is correctly named after language (note: called our_python because there was already a python folder)
  - [ ] File names follow `HelloLanguage` spec

(Optional) Server:
  - [ ] Follows correct protocol and works with official client
  - [ ] Accepts port as command line argument
  - [ ] Prints useful error on invalid arguments
  - [ ] Includes *useful* comments, no extraneous commented out code, etc

Comments or issues to be resolved:
Small fix: client file should be called HelloPython.py

**Comment by katiebramlett** [comment]
All changes have been resolved!

**Comment by twood02** [comment]
@katiebramlett and @sreya519 - your code looks good.  Please delete the `python_samples` directory since you aren't using it anymore. Then I will merge this.

**Comment by katiebramlett** [comment]
@twood02 Our python_sample_code directory has been removed. All set to merge. Thank you!

**Pull request merged**
