### PR TITLE
Hello scala

### PR DESCRIPTION
**Pull request by wzli1214**
This is the work of Weizhao Li & Zhuolun Gao.

### CODE REVIEW

**Comment by SiqiWang666** [comment]
Client:
Reviewed by: Huadong Hu(@HuadongHu)
 - [ ] Follows correct protocol and works with official server
 - [X] (Optional) Also works with Scala language server
 - [ ] Prints useful error if server is unavailable
 - [X] Accepts hostname and port as command line arguments
 - [X] Prints useful error on invalid arguments

Reviewed by: Siqi Wang(@SiqiWang666)
 - [X] Includes *useful* comments, no extraneous commented out code, etc
 - [X] No dead code. Excess code that is never run should be removed.
 - [X] No excess console output.
  
General:
Reviewed by: Hamid Reza (@Hamid-74)
  - [X] Readme explains socket API *clearly*
  - [X] Readme includes student names
  - [ ] Folder is correctly named after language
  - [ ] File names follow `HelloLanguage` spec

(Optional) Server:
Reviewed by: Siqi Wang(@SiqiWang666)
  - [X] Follows correct protocol and works with official client
  - [X] Accepts port as command line argument
  - [X] Prints useful error on invalid arguments
  - [X] Includes *useful* comments, no extraneous commented out code, etc

Comments or issues to be resolved:
Folder is not correctly named
Client source file's names should be like `helloScala`

**Comment by wzli1214** [comment]
Fixed by Weizhao Li:
·Follows correct protocol and makes scala client work with official server
·Prints useful error if server is unavailable
·Folder is correctly named after language
·File names follow HelloLanguage spec

Fixed by Zhuolun Gao:
·Follows correct protocol and makes scala server work with official client
·Folder is correctly named after language
·File names follow HelloLanguage spec

**Comment by twood02** [comment]
A few more small changes are needed:
 - delete the  `scala/.RpcClient.scala.swp` file
 - you deleted the README.md file from the root of the repo - please put that back

**Comment by wzli1214** [comment]
Hi professor,

We have made those changes.

   - delete the scala/.RpcClient.scala.swp file
   - you deleted the README.md file from the root of the repo - please put
   that back

Sincerely,

Weizhao Li


Tim Wood <notifications@github.com> 于2020年3月18日周三 下午9:47写道：

**Pull request merged**
